### ISSUE TITLE
[IMP] add translations files for `stock_allow_past_date` module

### ISSUE THREAD

**Issue by zaoral** [Vauxoo/addons-vauxoo#808]
module: stock_allow_past_date
## TODO
- [ ] create pot file
- [ ] create es.po with the corresponding translations
- [ ] create es_VE.po, es_MX.po and es_PA.po file sin blank

**Comment by zaoral** [comment]
This PR will be test in https://github.com/Vauxoo/yoytec/issues/984
