### ISSUE TITLE
[8.0] - Review list of unistallables módules.

### ISSUE THREAD

**Issue by nhomar** [Vauxoo/addons-vauxoo#918]
- [ ] - 2. invoice_cancel_islr: Module not installable
- [ ] - 3. account_move_line_address: Module not installable
- [ ] - 4. stock_purchase_expiry: Module not installable
- [ ] - 5. bank_iva_report: Module not installable
- [ ] - 6. recovery_attachments_bd: Module not installable
- [ ] - 7. mrp_webkit_report_wizard: Module not installable
- [ ] - 8. Module partner_search_by_vat for series 8.0 belongs to another repository: https://github.com/ingadhoc/odoo-addons#8.0
- [ ] - 9. invoice_multicompany_report: Module not installable
- [ ] - 10. Module partner_credit_limit for series 8.0 belongs to another repository: https://github.com/ingadhoc/odoo-addons#8.0
- [ ] - 11. Module purchase_discount for series 8.0 belongs to another repository: https://github.com/OCA/purchase-workflow.git#8.0
- [ ] - 12. partner_property_accounts: Module not installable
- [ ] - 13. Module account_analytic_required for series 8.0 belongs to another repository: https://github.com/OCA/account-analytic.git#8.0
- [ ] - 14. purchase_multi_report: Module not installable
- [ ] - 15. mrp_bom_subproduct_cost: Module not installable
- [ ] - 16. Module purchase_requisition_department for series 8.0 belongs to another repository: https://github.com/OCA/department.git#8.0
- [ ] - 17. issue_view: Module not installable
- [ ] - 18. account_voucher_tax: unmet dependency account_move_line_base_tax for series 8.0
- [ ] - 19. hr_expense_replenishment_tax: unmet dependency account_voucher_tax for series 8.0
- [ ] - 20. account_reconcile_advance_tax: unmet dependency account_voucher_tax for series 8.0
- [ ] - 21. invoice_cancel_iva: unmet dependency l10n_ve_withholding_iva for series 8.0
- [ ] - 22. account_move_line_base_tax: unmet dependency l10n_mx_account_tax_category for series 8.0
- [ ] - 23. account_voucher_tax_sat: unmet dependency account_voucher_tax for series 8.0
- [ ] - 24. account_tax_importation: unmet dependency account_voucher_tax for series 8.0
- [ ] - 25. account_update_amount_tax_in_move_lines: unmet dependency account_move_line_base_tax for series 8.0

**Comment by alan196** [comment]
@xluiisx @SaraiOsorio

**Comment by zaoral** [comment]
@nhomar seems like you miss the first item: module number 1 do not appeas in the view

**Comment by nhomar** [comment]
no it was a blank line in the copy paste.
